// Generated by gencpp from file morai_msgs/MoraiSimpProcSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAISIMPPROCSRV_H
#define MORAI_MSGS_MESSAGE_MORAISIMPPROCSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/MoraiSimpProcSrvRequest.h>
#include <morai_msgs/MoraiSimpProcSrvResponse.h>


namespace morai_msgs
{

struct MoraiSimpProcSrv
{

typedef MoraiSimpProcSrvRequest Request;
typedef MoraiSimpProcSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoraiSimpProcSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::MoraiSimpProcSrv > {
  static const char* value()
  {
    return "6d340598acf4b7d6e6f913c45512bf48";
  }

  static const char* value(const ::morai_msgs::MoraiSimpProcSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::MoraiSimpProcSrv > {
  static const char* value()
  {
    return "morai_msgs/MoraiSimpProcSrv";
  }

  static const char* value(const ::morai_msgs::MoraiSimpProcSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::MoraiSimpProcSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSimpProcSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSimpProcSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSimpProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimpProcSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSimpProcSrvRequest> should match
// service_traits::DataType< ::morai_msgs::MoraiSimpProcSrv >
template<>
struct DataType< ::morai_msgs::MoraiSimpProcSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSimpProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimpProcSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::MoraiSimpProcSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSimpProcSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSimpProcSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSimpProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimpProcSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSimpProcSrvResponse> should match
// service_traits::DataType< ::morai_msgs::MoraiSimpProcSrv >
template<>
struct DataType< ::morai_msgs::MoraiSimpProcSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSimpProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimpProcSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAISIMPPROCSRV_H
